import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/navbar";
import styles from "../styles/Home.module.css";
import Tables from "../components/stocktable";
import React from 'react';
import CustomTable from "../components/stocktable";



export default function Home() {
  return (


    <div>
      <Navbar/>
      <div className={styles.container}>
        <Head>
          <title>Landing Page</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/* <div> 
        <h1 className={styles.headers}> Sentiment Analysis </h1> kwlkwmelkmelkmelkwmelmwlkemlw
        </div> */}

        <div className={styles.stocks}> 
          
          <h2 className={styles.headers}> Top 10 Stocks </h2>
          <CustomTable/>
          
        </div>
        <div className={styles.stocks}> 
          <h2 className={styles.headers}> Bottom 10 Stocks </h2>
          <CustomTable/>

        </div>

      



        

        

      </div>
    </div>
  );
}
